# Generated by Django 5.1.2 on 2025-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
