# Generated by Django 5.2.1 on 2025-06-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_alter_checkin_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
